# -*- coding: utf-8 -*-
"""Rag_Debug.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sCFnJQQRMjXIB9l61bmoBvj6qpQm2_o5
"""

from langchain.globals import set_debug
set_debug(True)